spring:
  jpa:
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://mydb:3306/music"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

